apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: memcached
  name: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: memcached
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: memcached
    spec:
      containers:
        - args:
            - -I
            - 1M
          image: memcached:1.6.26-alpine
          livenessProbe:
            exec:
              command:
                - echo stats | nc 127.0.0.1 11211
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 90
          name: memcached
      restartPolicy: Always
