apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx:1.25.4-alpine
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-cm0
              readOnly: true
              subPath: nginx.conf
            - mountPath: /var/cache/nginx
              name: sentry-nginx-cache
            - mountPath: /var/www
              name: sentry-nginx-www
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: nginx.conf
                path: nginx.conf
            name: nginx-cm0
          name: nginx-cm0
        - name: sentry-nginx-cache
          persistentVolumeClaim:
            claimName: sentry-nginx-cache
        - name: sentry-nginx-www
          persistentVolumeClaim:
            claimName: sentry-nginx-www
