apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - args:
            - postgres
            - -c
            - max_connections=100
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          image: postgres:14.11
          livenessProbe:
            exec:
              command:
                - pg_isready -U postgres
            failureThreshold: 10
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 90
          name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: sentry-postgres
      restartPolicy: Always
      volumes:
        - name: sentry-postgres
          persistentVolumeClaim:
            claimName: sentry-postgres
