apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: relay
  name: relay
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: relay
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: relay
    spec:
      containers:
        - image: getsentry/relay:nightly
          name: relay
          volumeMounts:
            - mountPath: /work/.relay
              name: relay-cm0
              readOnly: true
            - mountPath: /geoip
              name: relay-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - configMap:
            name: relay-cm0
          name: relay-cm0
        - configMap:
            name: relay-cm1
          name: relay-cm1
