apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sentry-secrets
  name: sentry-secrets
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
