apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: sentry-clickhouse
  name: sentry-clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
