apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: smtp
  name: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: smtp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: smtp
    spec:
      containers:
        - image: tianon/exim4
          name: smtp
          volumeMounts:
            - mountPath: /var/spool/exim4
              name: sentry-smtp
            - mountPath: /var/log/exim4
              name: sentry-smtp-log
      restartPolicy: Always
      volumes:
        - name: sentry-smtp
          persistentVolumeClaim:
            claimName: sentry-smtp
        - name: sentry-smtp-log
          persistentVolumeClaim:
            claimName: sentry-smtp-log
