apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: snuba-subscription-consumer-events
  name: snuba-subscription-consumer-events
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: snuba-subscription-consumer-events
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: snuba-subscription-consumer-events
    spec:
      containers:
        - args:
            - subscriptions-scheduler-executor
            - --dataset
            - events
            - --entity
            - events
            - --auto-offset-reset=latest
            - --no-strict-offset-reset
            - --consumer-group=snuba-events-subscriptions-consumers
            - --followed-consumer-group=snuba-consumers
            - --schedule-ttl=60
            - --stale-threshold-seconds=900
          env:
            - name: CLICKHOUSE_HOST
              value: clickhouse
            - name: DEFAULT_BROKERS
              value: kafka:9092
            - name: REDIS_HOST
              value: redis
            - name: SENTRY_EVENT_RETENTION_DAYS
              value: "90"
            - name: SNUBA_SETTINGS
              value: self_hosted
            - name: UWSGI_DISABLE_LOGGING
              value: "true"
            - name: UWSGI_MAX_REQUESTS
              value: "10000"
          image: getsentry/snuba:nightly
          name: snuba-subscription-consumer-events
      restartPolicy: Always
