apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: snuba-group-attributes-consumer
  name: snuba-group-attributes-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: snuba-group-attributes-consumer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: snuba-group-attributes-consumer
    spec:
      containers:
        - args:
            - rust-consumer
            - --storage
            - group_attributes
            - --consumer-group
            - snuba-group-attributes-consumers
            - --auto-offset-reset=latest
            - --max-batch-time-ms
            - "750"
            - --no-strict-offset-reset
          env:
            - name: CLICKHOUSE_HOST
              value: clickhouse
            - name: DEFAULT_BROKERS
              value: kafka:9092
            - name: REDIS_HOST
              value: redis
            - name: SENTRY_EVENT_RETENTION_DAYS
              value: "90"
            - name: SNUBA_SETTINGS
              value: self_hosted
            - name: UWSGI_DISABLE_LOGGING
              value: "true"
            - name: UWSGI_MAX_REQUESTS
              value: "10000"
          image: getsentry/snuba:nightly
          name: snuba-group-attributes-consumer
      restartPolicy: Always
