apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: subscription-consumer-events
  name: subscription-consumer-events
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: subscription-consumer-events
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: subscription-consumer-events
    spec:
      containers:
        - args:
            - run
            - consumer
            - events-subscription-results
            - --consumer-group
            - query-subscription-consumer
          command:
            - /etc/sentry/entrypoint.sh
          env:
            - name: COMPOSE_PROFILES
              value: feature-complete
            - name: DEFAULT_CA_BUNDLE
              value: /etc/ssl/certs/ca-certificates.crt
            - name: GRPC_DEFAULT_SSL_ROOTS_FILE_PATH_ENV_VAR
              value: /etc/ssl/certs/ca-certificates.crt
            - name: PYTHONUSERBASE
              value: /data/custom-packages
            - name: REQUESTS_CA_BUNDLE
              value: /etc/ssl/certs/ca-certificates.crt
            - name: SENTRY_CONF
              value: /etc/sentry
            - name: SENTRY_EVENT_RETENTION_DAYS
              value: "90"
            - name: SNUBA
              value: http://snuba-api:1218
            - name: VROOM
              value: http://vroom:8085
          image: sentry-self-hosted-local
          name: subscription-consumer-events
          volumeMounts:
            - mountPath: /data
              name: sentry-data
            - mountPath: /etc/sentry
              name: subscription-consumer-events-cm1
            - mountPath: /geoip
              name: subscription-consumer-events-cm2
              readOnly: true
            - mountPath: /usr/local/share/ca-certificates
              name: subscription-consumer-events-cm3
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: sentry-data
          persistentVolumeClaim:
            claimName: sentry-data
        - configMap:
            name: subscription-consumer-events-cm1
          name: subscription-consumer-events-cm1
        - configMap:
            name: subscription-consumer-events-cm2
          name: subscription-consumer-events-cm2
        - configMap:
            name: subscription-consumer-events-cm3
          name: subscription-consumer-events-cm3
