apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: symbolicator-cleanup
  name: symbolicator-cleanup
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: symbolicator-cleanup
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: symbolicator-cleanup
    spec:
      containers:
        - args:
            - 55 23 * * * gosu symbolicator symbolicator cleanup
          image: symbolicator-cleanup-self-hosted-local
          name: symbolicator-cleanup
          volumeMounts:
            - mountPath: /data
              name: sentry-symbolicator
      restartPolicy: Always
      volumes:
        - name: sentry-symbolicator
          persistentVolumeClaim:
            claimName: sentry-symbolicator
