apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: symbolicator
  name: symbolicator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: symbolicator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: symbolicator
    spec:
      containers:
        - args:
            - run
            - -c
            - /etc/symbolicator/config.yml
          image: getsentry/symbolicator:nightly
          name: symbolicator
          volumeMounts:
            - mountPath: /data
              name: sentry-symbolicator
            - mountPath: /etc/symbolicator
              name: symbolicator-cm1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: sentry-symbolicator
          persistentVolumeClaim:
            claimName: sentry-symbolicator
        - configMap:
            name: symbolicator-cm1
          name: symbolicator-cm1
